baseURL = 'https://cymk8.github.io/'
languageCode = 'en-us'
title = 'Lessons'

[taxonomies]
# Use singular rather than plural for default taxonomies
tag = "tag"
category = "category"

[caches]
  [caches.images]
    dir = ':cacheDir/images'